import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { JSX, ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Posts Service',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): JSX.Element {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta name='viewport' content='width=device-width' />
        <body className={inter.className}>{children}</body>
      </head>
    </html>
  );
}
