import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { DefaultSeo } from 'next-seo';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang='en'>
      <head>
        <meta charSet='utf-8' />
        <meta name='viewport' content='width=device-width' />
        <DefaultSeo
          title='Posts Service'
          description='Best posts in the Tambov City'
          openGraph={{
            type: 'website',
            locale: 'en_IE',
            url: 'localhost:3000',
            siteName: 'Post Service',
          }}
          twitter={{
            handle: '@handle',
            site: '@site',
            cardType: 'any_image',
          }}
        />
        <body className={inter.className}>{children}</body>
      </head>
    </html>
  );
}
